---
- name: Install Memcache, Start and enable svc
  hosts: mcsrvgrp  # Ensure this group includes your memcached servers
  gather_facts: no
  tasks:
    - name: Install memcache
      apt:
        name: memcache
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - package

    - name: Start and enable the memcached service
      service:
        name: memcached
        state: started
        enabled: yes
      tags:
        - package

    - name: Enable remote login to memcached
      lineinfile:
        path: /etc/memcached.conf
        regexp: "^-l"
        line: "-l 0.0.0.0"
        backup: yes
      notify:
        - Restart memcached
      tags:
        - conf

  handlers:
    - name: Restart the memcached service
      service:
        name: memcached
        state: restarted
