- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Importing the variables file
      include_vars: vars/outputs

    - name: Importing the bashion variable
      include_vars: vars/bashion

    - name: Create a new EC2 key pair
      ec2_key:
        name: bashion_key
        region: "{{region}}"
      register: keyout

    - name: Store the key in the file
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: "./bashion-key.pem"
        mode: '0600'
      when: keyout.changed

    - name: Create security group rule for bashion
      ec2_group:
        name: bashion-sg
        description: sg with the description
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
            rule_desc: allow 22 from myip
      register: bashionSG_out

    - name: Print bashion_ami variable
      debug:
        msg: "{{ bashion_ami }}"


    - name: Creating Bashion Host
      ec2:
        key_name: bashion_key  # Ensure this matches the created key name
        region: "{{region}}"  # Ensure the region variable is defined
        instance_type: t2.micro
        image_id: "{{bashion_ami}}"  # Make sure this AMI ID is valid in the specified region
        wait: yes
        wait_timeout: 300
        instance_tags: # Corrected from instance_tag to instance_tags
          Name: "Bashion-proj"
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "Bashion-proj"
          Project: Projans
          Owner: Devops Team
        group_id: "{{ bashionSG_out.group_id }}"  # Ensure this variable is defined
        vpc_subnet_id: "{{ pubsub1_id }}"  # Ensure this variable is defined
      register: bashionHost_out


    - name: Debug variables
      debug:
        msg:
          - "bashion_ami: {{ bashion_ami }}"
          - "BastionSG_out.group_id: {{ BastionSG_out.group_id }}"

