- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import variables
      include_vars: vars/vpc-setup

    - name: VPC setup
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
        state: "{{state}}"
      register: vpcout

    - name: Subnet setup 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE1}}"
        cidr: "{{PUBSUB1CIDR}}"
        map_public: yes
        state: "{{state}}"
        tags:
          Name: proj-pub1
      register: pub1out

    - name: Subnet setup 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE2}}"
        cidr: "{{PUBSUB2CIDR}}"
        map_public: yes
        state: "{{state}}"
        tags:
          Name: proj-pub2
      register: pub2out

    - name: Subnet setup 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE3}}"
        cidr: "{{PUBSUB3CIDR}}"
        map_public: yes
        state: "{{state}}"
        tags:
          Name: proj-pub3
      register: pub3out

    - name: Subnet priv setup 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE1}}"
        cidr: "{{PRIVSUB1CIDR}}"
        map_public: yes
        state: "{{state}}"
        tags:
          Name: proj-priv1
      register: priv1out

    - name: Subnet priv setup 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE2}}"
        cidr: "{{PRIVSUB2CIDR}}"
        map_public: yes
        state: "{{state}}"
        tags:
          Name: proj-priv2
      register: priv2out

    - name: Subnet priv setup 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE3}}"
        cidr: "{{PRIVSUB3CIDR}}"
        map_public: yes
        state: "{{state}}"
        tags:
          Name: proj-priv3
      register: priv3out
