- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import variables
      include_vars: vars/vpc-setup

    - name: VPC setup
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
        state: "{{state}}"
      register: vpcout

    - name: Subnet setup
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.id}}"
        region: "{{region}}"
        availability_zone: "{{ZONE1}}"
        cidr: "{{PUBSUB1CIDR}}"
        map_public: yes
        state: "{{state}}"
        tags:
          Name: proj-pub1
      register: pub1out